### ISSUE TITLE
Is there a way to see if its working

### ISSUE THREAD

**Issue by hyderaliafzal** [vkatsar/loopback-redis-cache#2]

**Comment by vkatsar** [comment]
It is working great! Just test it. Try with a redis client to see the records and the ttl of them.

**Comment by hyderaliafzal** [comment]
can you share some useful material about its usage with redis client. Because I am new to it and don't know much about how I can set it up

**Comment by vkatsar** [comment]
Download here the client https://redisdesktop.com/

Connect to your redis server with your hostname, port and credentials and checkout database 0
