### ISSUE TITLE
Can cache param have a value other then number? if yes then what is expiration time?

### ISSUE THREAD

**Issue by hyderaliafzal** [vkatsar/loopback-redis-cache#3]

**Comment by vkatsar** [comment]
No. The cache param is the ttl in seconds for the redis. There is no default value.

**Comment by hyderaliafzal** [comment]
But if we don't want to specify the ttl then the key expired right away

**Comment by hyderaliafzal** [comment]
So if we want it to be in cache forever we should give cache an infinite time?

**Comment by hyderaliafzal** [comment]
If I call an api with different id and cache param has same value, first set key will be returned despite the id is changing in url.
